### ISSUE TITLE
Add express.js simple server skeleton and...

### ISSUE THREAD

**Issue by solyarisoftware** [rohitnairtech/nodejs-formaction-sdk-rasa#1]
Hi Rohit

I read about this repo [here](https://forum.rasa.com/t/how-to-handle-formaction-using-action-server/15303/10?u=solyarisoftware).  You did the `handleFormAction()` an that's great. 

Here my suggestion: 

  1. Why don't you add to the [expressjs](https://expressjs.com/) skeleton code on top, just to have a full runnable server!

  2. Besides/in general, I'd propose to show (in README.md) an usage demo example, to be used along with RASA documentation. Specifically I'd demostrate how to use  `handleFormAction()` for the [formbot](https://github.com/RasaHQ/rasa/tree/master/examples/formbot) RASA example.
  
If I can  I'll try to contribute, with the goal to have a complete RASA action server in nodejs :)

Thanks / giorgio

**Comment by rohitnairtech** [comment]
Hi Giorgio,

Thanks for reaching out, I would love to implement the suggested changes.

Also open to the idea of having a contributor to make a full fledged action
SDK on nodejs.

Let's get in touch.

Warm regards,
Rohit N

**Comment by solyarisoftware** [comment]
Thanks to you. If you will share the update I'll feedback.

**Comment by rohitnairtech** [comment]
Hi,

Can I have your github profile name or email address?

Warm regards,
Rohit N

**Comment by solyarisoftware** [comment]
here you go: https://github.com/solyarisoftware

**Comment by rohitnairtech** [comment]
Hey @solyarisoftware I have added 'expressjs skeleton code' in the README.md
